import prisma from "../prisma/prisma";
import Head from "next/head";
import { GetStaticProps } from "next";
import { User } from "@prisma/client";

interface IProps {
  user: User;
}

export const getStaticProps: GetStaticProps = async () => {
  const user = await prisma.user.findUnique({ where: { id: 1 } });

  return {
    props: { user },
    revalidate: 10,
  };
};

const Home: React.FC<IProps> = ({ user }) => {
  console.log(user);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Folkcenter</h1>
        <h3>Nome: {user?.name}</h3>
        <p>Email: {user?.email}</p>
      </main>

      <footer>
        <p>Footer</p>
      </footer>
    </div>
  );
};

export default Home;
